name: Checkout and setup
description: Check out the repo and perform setup steps
runs:
  using: composite
  steps:
      - id: cache-asdf
        uses: actions/cache@v2
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/.tool-versions') }}
        if: github.actor != 'nektos/act'
      - id: asdf-dir-exists
        shell: bash
        run: |
          if [ -d "$HOME/.asdf/bin" ]; then
            echo "::set-output name=asdf-dir-exists::true"
          else
            echo "::set-output name=asdf-dir-exists::false"
          fi
      - id: set-path
        shell: bash
        run: |
          echo "$HOME/.asdf/bin" >> $GITHUB_PATH
          echo "$HOME/.asdf/shims" >> $GITHUB_PATH
        if: steps.asdf-dir-exists.outputs.asdf-dir-exists == 'true'
      - id: asdf-install
        uses: asdf-vm/actions/install@v1
      - id: install-tflint
        uses: terraform-linters/setup-tflint@v1
      - id: install-deps
        shell: bash
        run: ./script/install_deps.sh
