on: [push, pull_request]
jobs:
  pre-commit-all:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: setup
        uses: ./.github/actions/setup
      - id: pre-commit-all
        run: pre-commit run --all-files
  test:
    needs: [pre-commit-all]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: setup
        uses: ./.github/actions/setup
      # enable when secrets are set up
      # - name: go_test
      #   run: go test ./test/ -v -timeout 30m
