on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go_setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: gofmt
        run: gofmt -s -l $(find . -name '*.go' -type f -print)
      - name: terraform_fmt
        run: terraform fmt -recursive -diff
