on: [push, pull_request]
jobs:
  pre-commit-all:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          # Get 2 previous commits in case we want to check for changed files
          fetch-depth: 2
      - id: setup
        uses: ./.github/actions/setup
      - id: cache-pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - id: pre-commit-all
        run: pre-commit run --all-files
  test:
    needs: [pre-commit-all]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          # Get 2 previous commits in case we want to check for changed files
          fetch-depth: 2
      - id: terraform-files-changed
        uses: tj-actions/changed-files@v13.1
        with:
          files: |
            .github/workflows/ci.yml
            examples/**/*.tf
            modules/**/*.tf
            modules/**/*.tpl
            test/*.go
            go.mod
            go.sum
            .tool-versions
            requirements-*.txt
            script/*.sh
      - id: setup
        uses: ./.github/actions/setup
        if: steps.terraform-files-changed.outputs.any_changed == 'true'
      - name: go_test
        run: go test ./test/ -v -timeout 30m
        if: steps.terraform-files-changed.outputs.any_changed == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
